#!/usr/bin/env bash
export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

function addBashAlias {
    BASH_RC_PATH=$HOME/.bashrc
    backupFile "$BASH_RC_PATH"
    newAlias="alias $1=\"$2\""
    grep -qF "$newAlias" "$BASH_RC_PATH" || echo "$newAlias" >> "$BASH_RC_PATH"
    source $BASH_RC_PATH
}

function addBashPath {
    BASH_RC_PATH=$HOME/.bashrc
    backupFile "$BASH_RC_PATH"
    newPath="export PATH=$1:\$PATH"
    bash -c "grep -q -F '$newPath' $BASH_RC_PATH || echo '$newPath' >> $BASH_RC_PATH"
    source $BASH_RC_PATH
}

function backupFile {
    if [ ! -f $1.ORIGINAL ]; then
        cp $1 $1.ORIGINAL
    fi
}

function installAnacondaPython {
    ANACONDA_DIR=$DIR/anaconda
    ANACONDA_URL='https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh'
    ANACONDA_INSTALLER=$DIR/$(basename $ANACONDA_URL)
    rm -f $ANACONDA_INSTALLER
    if [ -d  "$ANACONDA_DIR" ]; then
       return
    fi
    if [ ! -f "$ANACONDA_INSTALLER" ]; then
        wget $ANACONDA_URL -O $ANACONDA_INSTALLER
    fi
    chmod +x $ANACONDA_INSTALLER
    $ANACONDA_INSTALLER -b -p $ANACONDA_DIR
    rm -f $ANACONDA_INSTALLER
    addBashPath "$ANACONDA_DIR/bin"
    $ANACONDA_DIR/bin/conda install -y -c anaconda paramiko
    $ANACONDA_DIR/bin/conda install -y -c anaconda requests
}

function installDependencies {
    sudo yum install bzip2 -y
    sudo yum install wget -y
}

function installOracleJava {
    JAVA_URL='http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64
.rpm'
    JAVA_INSTALLER=$DIR/$(basename $JAVA_URL)
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=acc
ept-securebackup-cookie" "$JAVA_URL" -O "$JAVA_INSTALLER"
    sudo yum localinstall $JAVA_INSTALLER -y
    rm -f $JAVA_INSTALLER
}

function installVim {
    sudo yum install vim -y
    cat << 'EOL' > ~/.vimrc
filetype plugin indent off
set tabstop=4
set shiftwidth=4
set expandtab
set vb t_vb=
set background=dark
autocmd Filetype html setlocal ts=4 sts=4 sw=4 expandtab
autocmd Filetype java setlocal ts=4 sts=4 sw=4 expandtab
autocmd Filetype javascript setlocal ts=4 sts=4 sw=4 expandtab
autocmd Filetype php setlocal ts=4 sts=4 sw=4 expandtab
autocmd Filetype python setlocal ts=4 sts=4 sw=4 expandtab
autocmd Filetype yaml setlocal ts=2 sts=2 sw=2 expandtab
EOL
}

function restoreFile {
    if [ -f $1.ORIGINAL ]; then
        cp $1.ORIGINAL $1
    fi
}
